# --- Weather Dataset ---

VALID_WIND_DIRECTIONS = {
    "N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
    "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"
}

# --- Medical Dataset ---

MEDICAL_SPECIALTY_VALUES = [
    "InternalMedicine",
    "Cardiology",
    "Family/GeneralPractice",
    "Surgery-General",
    "Orthopedics-Reconstructive",
    "Pediatrics",
    "Surgery-Cardiovascular/Thoracic",
    "Pediatrics-Pulmonology",
    "Urology",
    "Emergency/Trauma",
    "Psychiatry",
    "Pulmonology",
    "Pediatrics-Endocrinology",
    "Orthopedics",
    "Hematology/Oncology",
    "Surgery-Neuro",
    "Nephrology",
    "ObstetricsandGynecology",
    "Otolaryngology",
    "Pediatrics-CriticalCare",
    "PhysicalMedicineandRehabilitation",
    "Gastroenterology",
    "Obsterics&Gynecology-GynecologicOnco",
    "Surgery-Plastic",
    "Surgery-Colon&Rectal",
    "Pediatrics-Neurology",
    "Osteopath",
    "Endocrinology",
    "AllergyandImmunology",
    "Surgery-Vascular",
    "Radiology",
    "Anesthesiology-Pediatric",
    "InfectiousDiseases",
    "Surgery-Maxillofacial",
    "Oncology",
    "Neurology",
    "Surgery-Thoracic",
    "Gynecology",
    "Surgeon",
    "Surgery-Pediatric",
    "Psychiatry-Addictive",
    "Surgery-Cardiovascular",
    "Anesthesiology",
    "PhysicianNotFound",
    "Hematology",
    "Podiatry",
    "Proctology",
    "Ophthalmology",
    "Rheumatology",
    "Psychology",
    "Obstetrics",
    "Dentistry",
    "SurgicalSpecialty",
]

ADMISSION_TYPE_DESC_VALUES = [
    'Emergency',
    'Not Available',
    'Urgent',
    'Elective',
    'Not Mapped',
    'Newborn',
]

ADMISSION_SOURCE_DESC_VALUES = [
    'Emergency Room',
    'Not Available',
    'Clinic Referral',
    'Transfer from a hospital',
    'Physician Referral',
    'Transfer from a Skilled Nursing Facility (SNF)',
    'Transfer from another health care facility',
    'HMO Referral',
    'Court/Law Enforcement',
    'Not Available',
    'Extramural Birth',
]

DISCHARGE_DISPOSITION_DESC_VALUES = [
    'Discharged to home',
    'Discharged/transferred to a long term care hospital.',
    'Discharged/transferred to SNF',
    'Discharged/transferred to home with home health service',
    'Expired',
    'Discharged/transferred to home under care of Home IV provider',
    'Discharged/transferred to another rehab fac including rehab units of a hospital .',
    'Discharged/transferred to another short term hospital',
    'Left AMA',
    'Discharged/transferred to another type of inpatient care institution',
    'Hospice / home',
    'Discharged/transferred to ICF',
    'Discharged/transferred/referred another institution for outpatient services',
    'Discharged/transferred/referred to this institution for outpatient services',
    'Hospice / medical facility',
    'Not Mapped',
    'Still patient or expected to return for outpatient services',
    'Unknown/Invalid',
    'Expired in a medical facility. Medicaid only, hospice.',
    'Discharged/transferred within this institution to Medicare approved swing bed',
    'Admitted as an inpatient to this hospital',
    'Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.',
]